apiVersion: v1
kind: Pod
metadata:
  name: microservice-libreria-pod
  labels: 
    app: microservice-libreria
    type: microservice
spec:
  containers:
  - name: microservice-libreria-app
    image: 454874477/serviciosapilibreria:latest
    ports:
      - containerPort: 80