apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels: 
    app: microservice-libreria
    type: database
spec:
  containers:
  - name: mongo
    image: mongo:5.0.8
    comand:
    - /bin/bash
    - -c
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      value: "jguzman"
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: "$VaxiDrez2025"
    ports:
      - containerPort: 27017